### ISSUE TITLE
worrisome version numbering

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#27]
i just did an update and 0.7.6 jumped to 15.0.0 on PyPi

same thing on the github tag.

there's no changelog or explanation for this numbering (which is odd).

**Comment by mahmoud** [comment]
Hey! Don't worry, very much intentional. Seeing how ashes is in production in so many places and getting installed thousands of times per month, I figured it was time for a major release version. Seeing as there's zero plans for API breakage and a pretty mature development pace, I've chosen to go with calendar versioning for the major version and semantic versioning for minor and micro. Future bugfix versions will be 15.0.1, 15.0.2, etc, whereas future feature versions will be 15.1.0, 15.2.0, etc., until we tick over to next year.

I've got a blog post about versioning philosophy in the works, as well as a belated release announcement for ashes. It was all supposed to happen a bit sooner, but I got tapped for an O'Reilly project that has been occupying a lot of my thought processes. 

Hopefully this wasn't too much of an inconvenience, thanks for understanding!

**Comment by jvanasco** [comment]
Ah, ok!  I've never used a project before with Calendar numbering.

2 small suggestions:
1. Update the readme.rst to note that you're using calendar numbering now.
2. Leave this ticket open until you do (otherwise it won't show up on the initial Issues page, and someone else might bring it up)
